import{i as n,S as d}from"./assets/vendor-8c59ed88.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function l(e){if(e.ep)return;e.ep=!0;const a=r(e);fetch(e.href,a)}})();const m=t=>`
  <li class="gallery-card"><a class="gallery-link" href="${t.largeImageURL}">
    <img class="gallery-img" src="${t.webformatURL}" alt="${t.tags}"/>
</a><div class ="card-data">  <ul class="data-list"><li class="image-data"><p class="image-data-text">Views</p><p class="image-data-text">${t.views}</p></li>
  <li class="image-data"><p class="image-data-text">Likes</p><p class="image-data-text">${t.likes}</p></li>
  <li class="image-data"><p class="image-data-text">Comments</p><p class="image-data-text">${t.comments}</p></li>
  <li class="image-data"><p class="image-data-text">Downloads</p><p class="image-data-text">${t.downloads}</p></li>
  </ul></div></li>
  `,p="https://pixabay.com/api/?key=45485539-1e2d85f159a7ac8a3c50871fa",u=t=>fetch(`${p}&q=${t}&image_type=photo&orientation=horizontal&safesearch=true`).then(s=>{if(!s.ok)throw new Error(s.status);return s.json()}),o=document.querySelector(".search-form"),g=document.querySelector(".gallery"),c=document.querySelector(".loader"),f=t=>{t.preventDefault(),c.classList.add("is-open");const s=o.elements.user_query.value;u(s).then(r=>{r.total===0&&(c.classList.remove("is-open"),o.reset(),n.show({message:"❌ Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"}));const l=r.hits.map(e=>m(e)).join("");o.reset(),c.classList.remove("is-open"),g.innerHTML=l,new d(".gallery-link",{captions:!0,captionsData:"alt",captionDelay:250}).refresh()}).catch(r=>{console.log(r)})};o.addEventListener("submit",f);
//# sourceMappingURL=commonHelpers.js.map
